typography_spectrum: 0.4958257
color:
  brandColors:
    - '#579BD8'
    - '#D3DBE8'
    - '#10150F'
    - '#9EA659'
    - '#916C51'
  brandStrength: 0.4531915
  lightness: 0.3957447
  rhythmicContrast: 0.4531915
  saturation: 0.5765957
layout_spectrum: 0.20477
author:
  name: carlos Tapia
  email: carlos.tapia@societyagency.com
  url: www.societyagency.com.mx
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a493d919-3600-4842-9ce1-168b91fc9e16.jpg
name: Society
favicon: null
title: Society Agency
description: Power by IPG Mediabrands
