typography_spectrum: 0.4958257
color:
  brandColors:
    - '#579BD8'
    - '#D3DBE8'
    - '#10150F'
    - '#9EA659'
    - '#916C51'
  brandStrength: 0.4531915
  lightness: 0.3957447
  rhythmicContrast: 0.4531915
  saturation: 0.5765957
layout_spectrum: 0.20477
name: Society
title: Society Agency
description: Power by IPG Mediabrands
